import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './(consistentPages)/nav/Nav'
import Trends from './(consistentPages)/trends/Trends'
import {DataGet} from '@/app/(context)/DataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' flex w-screen py-2'>
        <DataGet>
        <Nav />
        {children}
        <Trends />
        </DataGet>
        </body>
    </html>
  )
}
