import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './(consistentPages)/nav/Nav'
import Trends from './(consistentPages)/trends/Trends'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' flex w-screen'>
        <Nav />
        {children}
        <Trends />
        </body>
    </html>
  )
}
